[project]
name = "jaxagents"
version = "0.0.1"
authors = [
  { name="Antonis Mavritsakis (amavrits)", email="amavrits@gmail.com" },
]
description = "JAX implementation of Reinforcement Learning agents"
readme = ""
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/amavrits/jax-agents"
Issues = ""